name: Deploy docs to GitHub Pages

on:
  pull_request:
    types:
      - labeled

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    if: |
      ((github.event.pull_request.state == 'open') && 
      (github.base_ref == 'main') &&
      (contains(github.event.pull_request.labels.*.name, 'documentation')))

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install mdBook
        run: cargo install mdbook

      - name: Build HTML with mdBook
        run: docs/doc_converter.sh

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/book